version: "3"

services:
  mdm-postgres:
    container_name: mdm-postgres
    build:
      context: ./mdm-postgres
      dockerfile: Dockerfile
    image: mdm-postgres:1.0
    environment:
      - POSTGRES_DB=mdm
      - POSTGRES_USER=mdmdbuser
      - POSTGRES_PASSWORD=test12
      - POSTGRES_PORT=5432
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mdm-client-jpro:
    container_name: mdm-client-jpro
    build:
      context: mdm-client
      dockerfile: Dockerfile
    image: mdm-client-jpro:1.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mdm-postgres:5432/mdm
      - SPRING_DATASOURCE_USERNAME=mdmdbuser
      - SPRING_DATASOURCE_PASSWORD=test12
      - JPRO_SERVER_PORT=80
    ports:
      - 8080:80
    depends_on:
      - mdm-postgres

volumes:
  postgres-data: