spring:
  profiles:
    active: local

  jackson:
    default-property-inclusion: non_null
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    generator:
      write_bigdecimal_as_plain: true
    mapper:
      sort_properties_alphabetically: true # for better testability
    serialization:
      indent_output: true
    deserialization:
      fail-on-unknown-properties: false # allow it so that we can iterate faster for the prototype

  # start service mdm-postgres inside ./docker-compose.yml file to spin up postgres db with preconfigured application schema
  datasource:
    url: jdbc:postgresql://localhost:5433/mdm
    username: mdmdbuser
    password: test12
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # default_schema: mdm

  flyway:
    enabled: false

management:
  metrics:
    enable:
      tomcat: false
      jvm: false
      process: false
      hikaricp: false
      system: false
      jdbc: false
      logback: false
    web:
      server:
        request:
          autotime:
            enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      base-path: /internal
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
        exclude:
          - loggers
  endpoint:
    health:
      show-details: always
      sensitive: false
      db:
        enabled: true
      defaults:
        enabled: true
      diskspace:
        enabled: true

logging:
  level:
    root: info
    io.swagger.models.parameters.AbstractSerializableParameter: error

---

spring:
  profiles: local

---

spring:
  profiles: staging

---

spring:
  profiles: it

  flyway:
    enabled: true
    locations: classpath:testdb/migration

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        default_schema: